#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

targets=`find . -maxdepth 1 -type d -name "0*"`
for d in $targets; do
  cases=`find $d -maxdepth 1 -type d -name "*Case"`

  for c in $cases; do
    cd $c
      foamCleanTutorials
    cd -
  done
done

echo "Clean all test done"
